name: Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create Release and Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      # Needed for python-semantic-release to create a release
      contents: write
      # Needed for trusted publishing to PyPI
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # This is required for python-semantic-release to be able to analyze commits
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release
          pip install .

      - name: Create Release and Publish
        env:
          # This token is required to create a GitHub release.
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release publish